import javax.swing.JOptionPane;

/**
 *
 * @author Parasite
 */
public class AddBed extends javax.swing.JFrame {
    
    private Clinic clinic;

    /** Creates new form AddBed1 */
    public AddBed(Clinic clinic) {
        this.clinic = clinic;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    public AddBed() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        infoTF2 = new javax.swing.JLabel();
        roomTF = new javax.swing.JTextField();
        bedNumberTF = new javax.swing.JTextField();
        addBedB = new javax.swing.JButton();
        cancelB = new javax.swing.JButton();
        infoTF1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Bed");
        setResizable(false);

        infoTF2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        infoTF2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoTF2.setText("Bed Number");

        roomTF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        roomTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        bedNumberTF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bedNumberTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        addBedB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addBedB.setText("ADD BED");
        addBedB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBedBActionPerformed(evt);
            }
        });

        cancelB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cancelB.setText("CANCEL");
        cancelB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBActionPerformed(evt);
            }
        });

        infoTF1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        infoTF1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoTF1.setText("Room");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(infoTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(roomTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(infoTF2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bedNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addBedB, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelB, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bedNumberTF, infoTF1, infoTF2, roomTF});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addBedB, cancelB});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(infoTF2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bedNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBedB, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelB, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bedNumberTF, infoTF1, infoTF2, roomTF});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addBedB, cancelB});

        pack();
    }//GEN-END:initComponents

    private void addBedBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBedBActionPerformed
        if(roomTF.getText().trim().length()==0 || bedNumberTF.getText().trim().length() == 0){
            JOptionPane.showMessageDialog(null, "All fields are mandatory", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            if(roomTF.getText().trim().length() >10){
                JOptionPane.showMessageDialog(null, "Room description too long! Must be 1-10 characters!", "Error", JOptionPane.ERROR_MESSAGE);
            }else{
                if(bedNumberTF.getText().trim().length() >10){
                    JOptionPane.showMessageDialog(null, "Bed description too long! Must be 1-10 characters!", "Error", JOptionPane.ERROR_MESSAGE);
                }else{

                    
                    if(clinic.getBedMap().containsKey(roomTF.getText().trim() +" " + bedNumberTF.getText().trim())){
                        JOptionPane.showMessageDialog(null, "Bed already exists!", "Error", JOptionPane.ERROR_MESSAGE);
                        
                    }
                    else{
                        clinic.addBed(new Bed(roomTF.getText().trim(), bedNumberTF.getText().trim()));
                        JOptionPane.showMessageDialog(null, "Bed added successfully!","Bed added", JOptionPane.INFORMATION_MESSAGE);
                        new BedScreen(clinic);
                        this.dispose();
                    }

                }
            }
        }
    }//GEN-LAST:event_addBedBActionPerformed

    private void cancelBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBActionPerformed
        new BedScreen(clinic);
        this.dispose();
    }//GEN-LAST:event_cancelBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBedB;
    private javax.swing.JTextField bedNumberTF;
    private javax.swing.JButton cancelB;
    private javax.swing.JLabel infoTF1;
    private javax.swing.JLabel infoTF2;
    private javax.swing.JTextField roomTF;
    // End of variables declaration//GEN-END:variables

}
