import java.util.ArrayList;

import java.util.Vector;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Parasite
 */
public class AddPatient extends javax.swing.JFrame {
    
    private Clinic clinic;

    /** Creates new form AddPatient */


    public AddPatient() {
        initComponents();
    }
    
    public AddPatient(Clinic clinic) {
        this.clinic = clinic;
        initComponents();
        for(int i = 0 ; i < clinic.doctorList().size(); i++){
            doctorsCB.addItem(clinic.doctorList().get(i));
        }
        for(int i = 0 ; i < clinic.availableBedList().size(); i++){
            bedCB.addItem(clinic.availableBedList().get(i));
        }
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        diagnosisTF = new javax.swing.JTextField();
        lastNameTF = new javax.swing.JTextField();
        firstNameTF = new javax.swing.JTextField();
        ssnTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        addPatientB = new javax.swing.JButton();
        goBackB = new javax.swing.JButton();
        comboBoxPN = new javax.swing.JPanel();
        bedCB = new JComboBox();
        doctorsCB = new JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Patient");
        setResizable(false);

        diagnosisTF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        diagnosisTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lastNameTF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lastNameTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        firstNameTF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        firstNameTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ssnTF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ssnTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Social Security Number");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("First Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Last Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Diagnosis");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Bed");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Doctor");

        addPatientB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addPatientB.setText("ADD PATIENT");
        addPatientB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientBActionPerformed(evt);
            }
        });

        goBackB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        goBackB.setText("GO BACK");
        goBackB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackBActionPerformed(evt);
            }
        });

        comboBoxPN.setLayout(new java.awt.GridLayout(2, 1, 0, 20));

        bedCB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bedCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Bed" }));
        bedCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bedCBActionPerformed(evt);
            }
        });
        comboBoxPN.add(bedCB);

        doctorsCB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        doctorsCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chose Doctor" }));
        comboBoxPN.add(doctorsCB);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(diagnosisTF)
                    .addComponent(ssnTF)
                    .addComponent(firstNameTF)
                    .addComponent(lastNameTF)
                    .addComponent(comboBoxPN, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                .addGap(91, 91, 91))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(addPatientB, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(goBackB, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addPatientB, goBackB});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ssnTF, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firstNameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lastNameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(diagnosisTF, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comboBoxPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPatientB, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goBackB, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addPatientB, goBackB});

        pack();
    }//GEN-END:initComponents

    private void goBackBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackBActionPerformed
        new PatientsScreen(clinic);
        this.dispose();
    }//GEN-LAST:event_goBackBActionPerformed

    private void addPatientBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientBActionPerformed
        if(ssnTF.getText().length()== 0 || lastNameTF.getText().length()== 0 || firstNameTF.getText().length() == 0 || diagnosisTF.getText().length() == 0 || doctorsCB.getSelectedIndex() == 0 || bedCB.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "All fields are mandatory", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            if(ssnTF.getText().length()>20){
                JOptionPane.showMessageDialog(null, "Social Security Number is too long! Must be between 1-20 characters!", "Error", JOptionPane.ERROR_MESSAGE); 
            }else{
                if(lastNameTF.getText().length()>30){
                    JOptionPane.showMessageDialog(null, "Last Name is too long! Must be between 1-50 characters!", "Error", JOptionPane.ERROR_MESSAGE);   
                }else{
                    if(firstNameTF.getText().length()>30){
                        JOptionPane.showMessageDialog(null, "First Name is too long! Must be between 1-50 characters!", "Error", JOptionPane.ERROR_MESSAGE); 
                    }else{
                        if(diagnosisTF.getText().length()>50){
                            JOptionPane.showMessageDialog(null, "Diagnosis is too long! Must be between 1-50 characters!", "Error", JOptionPane.ERROR_MESSAGE);
                        }else{
                            Bed tempbed =  (Bed) bedCB.getSelectedItem();
                            Doctor tempdoctor = (Doctor) doctorsCB.getSelectedItem();
                            clinic.addPatient(new Patient(ssnTF.getText(), firstNameTF.getText(),lastNameTF.getText(), diagnosisTF.getText(),tempbed, tempdoctor ));
                            new PatientsScreen(clinic);
                            this.dispose();                              
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_addPatientBActionPerformed

    private void bedCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bedCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bedCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null,
                                                                               ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null,
                                                                               ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null,
                                                                               ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null,
                                                                               ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPatientB;
    private JComboBox bedCB;
    private javax.swing.JPanel comboBoxPN;
    private javax.swing.JTextField diagnosisTF;
    private JComboBox doctorsCB;
    private javax.swing.JTextField firstNameTF;
    private javax.swing.JButton goBackB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField lastNameTF;
    private javax.swing.JTextField ssnTF;
    // End of variables declaration//GEN-END:variables

}
