/**
 *
 * @author Parasite
 */
public class PatientsScreen extends javax.swing.JFrame {
    
    private Clinic clinic;

    /** Creates new form PatientsScreen */
    public PatientsScreen() {
        initComponents();
    }
    
    public PatientsScreen(Clinic clinic) {
        this.clinic = clinic;
        initComponents();
        for(String key: clinic.getPatientMap().keySet()){
            patientsPN.add(new SinglePatientPN(this, clinic, clinic.getPatientMap().get(key)));
        }

        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jScrollPane1 = new javax.swing.JScrollPane();
        patientsPN = new javax.swing.JPanel();
        addNewPatB = new javax.swing.JButton();
        goBackB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Patients");
        setResizable(false);

        patientsPN.setLayout(new java.awt.GridLayout(clinic.getPatientMap().size() +4, 1));
        jScrollPane1.setViewportView(patientsPN);

        addNewPatB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addNewPatB.setText("ADD NEW PATIENT");
        addNewPatB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewPatBActionPerformed(evt);
            }
        });

        goBackB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        goBackB.setText("GO BACK");
        goBackB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(addNewPatB, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(goBackB, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addNewPatB, goBackB});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNewPatB, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goBackB))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addNewPatB, goBackB});

        pack();
    }//GEN-END:initComponents

    private void goBackBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackBActionPerformed
        new ClinicMainScreen(clinic);
        this.dispose();
    }//GEN-LAST:event_goBackBActionPerformed

    private void addNewPatBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewPatBActionPerformed
        new AddPatient(clinic);
        this.dispose();
    }//GEN-LAST:event_addNewPatBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null,
                                                                                   ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null,
                                                                                   ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null,
                                                                                   ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null,
                                                                                   ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientsScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewPatB;
    private javax.swing.JButton goBackB;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel patientsPN;
    // End of variables declaration//GEN-END:variables

}
