/**
 *
 * @author Parasite
 */
public class SinglePatientPN extends javax.swing.JPanel {
    
    private Clinic clinic;
    private PatientsScreen patientsscreen;
    private Patient patient;

    /** Creates new form SinglePatientPN */
    public SinglePatientPN() {
        initComponents();
    }
    
    public SinglePatientPN(PatientsScreen patientsscreen, Clinic clinic, Patient patient) {
        this.patientsscreen = patientsscreen;
        this.clinic = clinic;
        this.patient = patient;
        initComponents();
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        nameL = new javax.swing.JLabel();
        removeB = new javax.swing.JButton();
        diagnosisL = new javax.swing.JLabel();
        bedL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new java.awt.GridLayout(3, 2, 5, 5));

        nameL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nameL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameL.setText(patient.toString());
        add(nameL);

        removeB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        removeB.setText("Remove Patient");
        removeB.setToolTipText("Removes this patient from the clinic");
        removeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBActionPerformed(evt);
            }
        });
        add(removeB);

        diagnosisL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        diagnosisL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        diagnosisL.setText(patient.getDiagnosis());
        add(diagnosisL);

        bedL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bedL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bedL.setText(patient.getBed().toString());
        add(bedL);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Assigned Doctor :");
        add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(patient.getAssignedDoc().toString());
        add(jLabel2);
    }//GEN-END:initComponents

    private void removeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBActionPerformed
        clinic.removePatient(patient);
        new PatientsScreen(clinic);
        patientsscreen.dispose();

    }//GEN-LAST:event_removeBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bedL;
    private javax.swing.JLabel diagnosisL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel nameL;
    private javax.swing.JButton removeB;
    // End of variables declaration//GEN-END:variables

}
